---
name: test

on:
  push:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        elixir: ["1.9.x", "1.10.x"]
        erlang: ["21.x", "22.x"]
        os: [ubuntu-latest]
    name: test
    steps:
      - name: Setup elixir
        uses: actions/setup-elixir@v1.2.0
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.erlang }}

      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Get deps cache
        uses: actions/cache@v1
        with:
          path: deps/
          key: ${{ matrix.elixir }}_erl${{ matrix.erlang }}-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: ${{ matrix.elixir }}_erl${{ matrix.erlang }}-deps-

      - name: Get build cache
        uses: actions/cache@v1
        with:
          path: _build/test/
          key: ${{ matrix.elixir }}_erl${{ matrix.erlang }}-build-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: ${{ matrix.elixir }}_erl${{ matrix.erlang }}-build-

      - name: Install Dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
          mix compile

      - name: Lint & test
        run: |
          # mix cotton.lint
          mix test
          mix coveralls.json

      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
